[toolchain]
channel = "stable"
components = [
  "rustc",
  "cargo",
  "rustfmt",
  "rust-std",
  "rust-analyzer",
  "clippy",
  "rust-src",
]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "wasm32-unknown-unknown",
]
profile = "default"
